# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - joint_hombro
      - joint_hombro_codo
      - joint_codo
      - joint_codo_muneca
      - joint_muneca
      - joint_herramienta
    action_ns: follow_joint_trajectory
    default: true