# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    fobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fobot_arm_controller:
  ros__parameters:
    joints:
      - joint_hombro
      - joint_hombro_codo
      - joint_codo
      - joint_codo_muneca
      - joint_muneca
      - joint_herramienta
    command_interfaces:
      []
    state_interfaces:
      []